steps:
# Build a Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_ARTIFACTS_DIR/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA', '.']

# Image Push to Artifacts Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_ARTIFACTS_DIR/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA']
#Deploy into cloudfunction on GCP
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - functions
      - deploy
      - common-process
      - '--gen2'
      - '--region'
      - $_DEPLOY_REGION
      - '--source=legal-doc-ai/deployments/common-process'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--runtime=python38'
      - '--entry-point=hello_http'
      - '--memory'
      - $_MEMORY
      - '--cpu'
      - $_CPU
      - '--timeout'
      - '$_TIMEOUT'
      - '--concurrency'
      - $_CONCURRENCY
      - '--min-instances'
      - $_MIN_INSTANCES
      - '--max-instances'
      - $_MAX_INSTANCES
      - '--service-account'
      - $_SERVICE_ACCOUNT
      - '--set-env-vars'
      - $_SET_ENV_VARS
